services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ny_taxi_db
    volumes:
      - "/home/bibek/Desktop/Data_Engineering/Week_1/data_mapping_for_postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5000:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "8080:80"
      